accounts/urls.py
from django.urls import path

from .views import (
    register,
    login_user,
    login_register_user, 
    logout_user,
    profile, 
    add_delete_favourite,
    update_delete_review,
    validate_email,
)

# namespace = accounts

urlpatterns = [
    # Authentication
    path('login/', login_user, name='login'),
    path('register/', register, name='register'),
    path('login/register/', login_register_user, name='login-register'),
    path('logout/', logout_user, name='logout'),
    
    # Profile 
    path('account/', profile, name='profile'),
    # js validations
    path('ajax/validate/email/', validate_email, name='ajax-validate-email'),
    # favourites
    path('ajax/favourite/add/', add_delete_favourite, name='add-delete-favourite'),
    # Reviews
    path('ajax/review/<int:review_id>/update/delete/', update_delete_review, name='update-delete-review'),
]    

faq/urls.py
from django.urls import path

from .views import faq

# namespace = faq

urlpatterns = [
    path('faqs/', faq, name='faq'),
]

home/urls.py
from django.urls import path

from .views import index

# namespace = home

urlpatterns = [
    path('', index, name='index'),
]

product/urls.py
from django.urls import path

from .views import (
    product_detail, 
    product_variation, 
    product_images, 
    add_review , 
    update_review, 
    delete_review,
    product_user_rate, 
)

# namespace = product 

urlpatterns = [
    path('p/<str:product_slug>/', product_detail, name='product-detail'),
    path('ajax/p/<int:product_id>/variation/', product_variation, name='ajax-fetch-product-variation'),
    path('ajax/p/<int:product_id>/images/', product_images, name='ajax-fetch-product-images'),
    # Reviews
    path('ajax/p/review/add/', add_review, name='add-review'),
    path('ajax/p/review/update/', update_review, name='update-review'),
    path('ajax/p/review/delete/', delete_review, name='delete-review'),
    path('ajax/p/review/user/rate/', product_user_rate, name='ajax-fetch-product-user-rate'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static

from accounts.forms import (
        EmailValidationOnForgotPassword, 
        PasswordFieldsOnForgotPassword, 
        PasswordFieldsOnChangePassword,
    )


urlpatterns = [
    ## Django Admin
    path('admin/', admin.site.urls),

    ## Regular Endpoints
    # Accounts
    path('', include(('accounts.urls', 'accounts'), namespace='accounts')),
    # Product
    path('', include(('product.urls', 'product'), namespace='product')),
    # Cart
    path('', include(('cart.urls', 'cart'), namespace='cart')),
    # Order
    path('', include(('order.urls', 'order'), namespace='order')),
    # Checkout
    path('', include(('checkout.urls', 'checkout'), namespace='checkout')),
    # Home
    path('', include(('home.urls', 'home'), namespace='home')),
    # About
    path('', include(('about.urls', 'about'), namespace='about')),
    # FAQs
    path('', include(('faq.urls', 'faq'), namespace='faq')),
    
    # Password reset
    # 1- Submit password form                     // PasswordResetView.as_view() 
    # 2- Email sent success message               // PasswordResetDoneView.as_view()  
    # 3- Link to password reset form in email     // PasswordResetConfirmView.as_view() 
    # 4- password successfully changed message    // PasswordResetCompleteView.as_view()

    path('password/reset/', auth_views.PasswordResetView.as_view(
                                template_name='accounts/password_reset.html',
                                form_class=EmailValidationOnForgotPassword,),
                                name='password_reset'),
    path('password/reset/sent/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_sent.html',), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
                                template_name='accounts/password_reset_form.html',
                                form_class=PasswordFieldsOnForgotPassword,),
                                name='password_reset_confirm'),
    path('password/reset/complete/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_done.html',), name='password_reset_complete'),

    # Password change
    # 1- Submit password form                     // PasswordChangeView.as_view() 
    # 2- password successfully changed message    // PasswordChangeDoneView.as_view()
    path('password/change/', auth_views.PasswordChangeView.as_view(
                                template_name='accounts/password_change_form.html',
                                form_class=PasswordFieldsOnChangePassword,),
                                name='password_change'),
    path('password/change/complete/', auth_views.PasswordChangeDoneView.as_view(template_name='accounts/password_change_done.html',), name='password_change_done'),

    # Category
    path('', include(('category.urls', 'category'), namespace='category')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager


class UserManager(BaseUserManager):
    """
    Override user model manager.
    """
    def create_user(self, email, password=None, is_active=True, is_staff=False, is_superuser=False, is_previously_logged_in=False):
        """
        Take email, password, and create user.
        """
        if not email:
            raise ValueError('Users must have an email address')
        if not password:
            raise ValueError('Users must have a password')
        user_obj = self.model(email=self.normalize_email(email))
        user_obj.set_password(password)
        user_obj.is_active = is_active
        user_obj.is_staff_user = is_staff
        user_obj.is_superuser = is_superuser
        user_obj.previously_logged_in = is_previously_logged_in
        user_obj.save(using=self._db)
        return user_obj

    def create_staffuser(self, email, password=None):
        """
        Take email and password, and create staffuser.
        """
        user = self.create_user(email, password=password, is_staff=True)    
        return user

    def create_superuser(self, email, password=None):
        """
        Take email and password, and create superuser.
        """
        user = self.create_user(email, password=password, is_staff=True, is_superuser=True)    
        return user


class User(AbstractBaseUser):
    """
    User model.
    """
    email = models.EmailField(max_length=64, unique=True)
    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    is_active = models.BooleanField(default=True) # can login
    is_staff_user = models.BooleanField(default=False) # staff user non superuser
    is_superuser = models.BooleanField(default=False) # superuser
    timestamp = models.DateTimeField(auto_now_add=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = [] # USERNAME_FIELD and password are required by default.

    previously_logged_in = models.BooleanField(default=False)

    objects = UserManager()

    def __str__(self):
        return self.email

    def get_full_name(self):
        return self.email

    def get_short_name(self):
        return self.email  

    def has_perm(self, perm, obj=None):
        return True
    
    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_staff_user   

    @property
    def is_previously_logged_in(self):
        return self.previously_logged_in

accounts/forms.py
from django import forms
# from django.contrib.auth import password_validation
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import PasswordResetForm, SetPasswordForm, PasswordChangeForm


User = get_user_model()

class AddUserForm(forms.ModelForm):
    """
    User creation form class.
    """
    first_name = forms.CharField(
        label='',
        max_length=55, 
        widget=forms.TextInput(attrs={'class':'form-control', 'name':'firstname', 'required':True}),
    )
    last_name = forms.CharField(
        label='',
        max_length=55, 
        widget=forms.TextInput(attrs={'class':'form-control', 'name':'lastname', 'required':True}),
    )
    email = forms.EmailField(
        label='',
        max_length=60, 
        widget=forms.EmailInput(attrs={'class':'form-control js-validate-email', 'name':'email', 'required':True}),
    )
    email2 = forms.EmailField(
        label='',
        max_length=60, 
        widget=forms.EmailInput(attrs={'class':'form-control js-validate-email2', 'name':'confirm_email', 'required':True}),
    )
    password1 = forms.CharField(
        label='',
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password', 'class':'form-control js-validate-password1', 'required':True}),
    )
    password2 = forms.CharField(
        label='',
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password', 'class':'form-control js-validate-password2', 'required':True}),
    )

    class Meta:
        model   = User
        fields  = ['first_name', 'last_name', 'email', 'email2', 'password1', 'password2']    

    def clean_email2(self):
        """
        Validate emails.
        """
        email1 = self.cleaned_data.get("email")
        email2 = self.cleaned_data.get('email2') 
        # check if the two emails match.
        if email1 != email2:
            raise forms.ValidationError('The two email fields didn’t match.')
        # check if the email has already been used.  
        if User.objects.filter(email__iexact=email2).exists():
            raise forms.ValidationError("An account with this Email already exists.")
        return email2

    def clean_password2(self):
        """
        Validate passwords.
        """
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get('password2') 
        # check if the two passwords match.
        if password1 and password2:
            if password1 != password2:
                raise forms.ValidationError('The two password fields didn’t match.')
        return password2

class UpdateUserForm(forms.ModelForm):
    """
    Update User model form.
    """
    first_name = forms.CharField(
        label='First name',
        max_length=55, 
        widget=forms.TextInput(attrs={'class':'form-control', 'name':'first_name', 'required':True}),
    )
    last_name = forms.CharField(
        label='Last name',
        max_length=55, 
        widget=forms.TextInput(attrs={'class':'form-control', 'name':'last_name', 'required':True}),
    )
    email = forms.EmailField(
        label='Email address',
        max_length=60, 
        widget=forms.EmailInput(attrs={'class':'form-control js-validate-email', 'name':'email', 'required':True}),
    )

    class Meta:
        model  = User
        fields = ['first_name', 'last_name', 'email']

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request", None)
        super(UpdateUserForm, self).__init__(*args, **kwargs)    

    def clean_email(self):
        """
        Validate email.
        """
        email = self.cleaned_data.get("email")
        # check if the email has already been used.   
        if User.objects.filter(email__iexact=email).exclude(email__iexact=self.request.user.email).exists():
            raise forms.ValidationError("An account with this Email already exists.")
        return email

class EmailValidationOnForgotPassword(PasswordResetForm):
    """
    Override password reset form email field and its validation.
    """
    email = forms.EmailField(
        label='',
        max_length=255,
        widget=forms.EmailInput(attrs={'autocomplete': 'email', 'class':'form-control', 'name':'email', 'required': True})
    )

    def clean_email(self):
        """
        Validate email.
        """
        # fetch entered email.
        email = self.cleaned_data['email']
        # check if the entered email doesn't exist.
        if not User.objects.filter(email__iexact=email, is_active=True).exists():
            raise forms.ValidationError("Your email was entered incorrectly. Please enter it again.")
        return email


class PasswordFieldsOnForgotPassword(SetPasswordForm):
    """
    Override set password form password fields.
    """
    new_password1 = forms.CharField(
        label='',
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password', 'class':'form-control js-validate-password1 mb-2', 'required':True}),
        strip=False,
        # help_text=password_validation.password_validators_help_text_html(),
    )
    new_password2 = forms.CharField(
        label='',
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password', 'class':'form-control js-validate-password2', 'required':True}),
    )


class PasswordFieldsOnChangePassword(PasswordChangeForm):
    """
    Override password change form password fields.
    """
    old_password = forms.CharField(
        label='',
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'current-password', 'autofocus': True, 'class':'form-control mb-2', 'required':True}),
    )
    new_password1 = forms.CharField(
        label='',
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password', 'class':'form-control js-validate-password1 mb-2', 'required':True}),
        strip=False,
        # help_text=password_validation.password_validators_help_text_html(),
    )
    new_password2 = forms.CharField(
        label='',
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password', 'class':'form-control js-validate-password2', 'required':True}),
    )

templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% load category_tags %}

{% block title %}
<title>Login</title>
{% endblock title %}

{% block content %}

<div id="page-content">
    <!--Body Container-->
    <!--Breadcrumbs-->
    <div class="breadcrumbs-wrapper">
        <div class="container">
            <div class="breadcrumbs"><a href="{% url 'home:index' %}" title="Back to the home page">Home</a> <span
                    aria-hidden="true">|</span> <span>Login</span></div>
        </div>
    </div>
    <!--End Breadcrumbs-->
    <!--Page Title with Image-->
    <div class="page-title">
        <h1>Login</h1>
    </div>
    <!--End Page Title with Image-->
    <div class="container">
        <div class="row">
            <!--Main Content-->
            <div class="col-12 col-sm-12 col-md-6 col-lg-6 box order-2 order-md-1">
                <h3>New Customers</h3>
                <p>By creating an account with our store, you will be able to move through the checkout process faster,
                    store multiple shipping addresses, view and track your orders in your account and more.</p>
                <a href="{% url 'accounts:register' %}" class="btn">Create an account</a>
            </div>
            <div class="col-12 col-sm-12 col-md-6 col-lg-6 box order-1 order-md-2">
                <div class="mb-4">
                    {% redirected_url 'next' request.get_full_path as relative_url %}
                    <form method="post" 
                    {% if relative_url %}
                    action="{% url 'accounts:login' %}?next{{ relative_url.0 }}" 
                    {% else %}
                    action="{% url 'accounts:login' %}"
                    {% endif %}
                    id="CustomerLoginForm" accept-charset="UTF-8" class="contact-form">
                        {% csrf_token %}
                        <h3>Registered Customers</h3>
                        <p>If you have an account with us, please log in.</p>
                        <!-- Display success message -->
                        {% if messages %}
                        <div class="row">
                            <div class="col-12">
                            {% for message in messages %}
                                {% if 'register' in message.tags %}
                                    <div class='alert alert-success message' role="alert">{{ message }}</div>
                                {% endif %}
                            {% endfor %}
                            </div>
                        </div>    
                        {% endif %}   
                        <div class="row">
                            <div class="col-12 col-sm-12 col-md-12 col-lg-12">
                                <div class="form-group">
                                    <label for="CustomerEmail">Email <span class="required">*</span></label>
                                    <input type="email" name="email" placeholder="" id="CustomerEmail"
                                        class="" autocorrect="off" autocapitalize="off" autofocus required>
                                </div>
                            </div>
                            <div class="col-12 col-sm-12 col-md-12 col-lg-12">
                                <div class="form-group">
                                    <label for="CustomerPassword">Password <span class="required">*</span></label>
                                    <input type="password" value="" name="password" placeholder=""
                                        id="CustomerPassword" class="" required>
                                </div>
                            </div>
                        </div>
                        <!-- Display email error message -->
                        {% if messages %}
                        <div class="row pb-3">
                            <div class="col-12">
                            {% for message in messages %}
                                {% if 'login' in message.tags %}
                                    <div class="col-12 col-sm-12 col-md-12 col-lg-12 text-danger pl-0 pb-2" role="alert">
                                        <p class="error-message">
                                            <strong>{{ message }}</strong>
                                        </p>
                                    </div>
                                {% endif %}
                            {% endfor %}
                            </div>
                        </div>    
                        {% endif %}   
                        <div class="row">
                            <div class="text-left col-12 col-sm-12 col-md-12 col-lg-12">
                                <input type="submit" class="btn mb-3" value="Sign In">
                                <p class="mb-4">
                                    <a href="{% url 'password_reset' %}">Forgot your password?</a> &nbsp; | &nbsp;
                                    <a href="{% url 'accounts:register' %}" id="customer_register_link">Create account</a>
                                </p>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <!--End Main Content-->
        </div>

    </div>
    <!--End Body Container-->

</div>
<!--End Page Wrapper-->

{% endblock content %}

{% block scripts %}

    <script src="{% static 'assets/js/custom/accounts/login.js' %}"></script>

{% endblock scripts %}

templates/accounts/password_change_done.html
{% extends 'base.html' %}

{% block title %}
    <title>Password Change Done</title>
{% endblock title %}

{% block content %}

<div id="page-content">
  <!--Body Container-->
  <!--Breadcrumbs-->
  <div class="breadcrumbs-wrapper">
      <div class="container">
          <div class="breadcrumbs"><a href="{% url 'home:index' %}" title="Back to the home page">Home</a> <span
                  aria-hidden="true">|</span> <span>ٌPassword Change Done</span>
          </div>
      </div>
  </div>
  <!--End Breadcrumbs-->
  <!--Page Title with Image-->
  <div class="page-title">
      <h1>ٌٌPassword Change Done</h1>
  </div>
  <!--End Page Title with Image-->
  <div class="container">
      <div class="row">
          <!--Main Content-->
          <div class="col-12 col-sm-12 col-md-6 col-lg-6 box offset-md-3">
              <p>Your password has been changed successfully.</p>
              <div class="mb-4">
                  <div class="row">
                      <div class="text-left col-12 col-sm-12 col-md-12 col-lg-12">
                          <p>
                              <a href="/">« Back To Home Page</a>
                          </p>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </div>
</div>

{% endblock content %}

templates/accounts/password_change_form.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>Change Password</title>
{% endblock title %}

{% block content %}

<div id="page-content">
  <!--Body Container-->
  <!--Breadcrumbs-->
  <div class="breadcrumbs-wrapper">
    <div class="container">
      <div class="breadcrumbs"><a href="{% url 'home:index' %}" title="Back to the home page">Home</a> <span
          aria-hidden="true">|</span><span>Change Your Password</span>
      </div>
    </div>
  </div>
  <!--End Breadcrumbs-->
  <!--Page Title with Image-->
  <div class="page-title">
    <h1>Change your password</h1>
  </div>
  <!--End Page Title with Image-->
  <div class="container">
    <div class="row">
      <!--Main Content-->
      <div class="col-12 col-sm-12 col-md-6 col-lg-6 box offset-md-3">
        <p>You are only one step a way from your new password, change your password now.</p>
        <div class="mb-4">
          <form method="post" action="." accept-charset="UTF-8" class="contact-form">
            {% csrf_token %}
            <div class="row">
              <div class="col-12 col-sm-12 col-md-12 col-lg-12">
                <div class="form-group">
                  <label for="id_old_password">Old Password <span class="required">*</span></label>
                  {{ form.old_password }}
                </div>
                <!-- Display old password error message -->
                {% if form.old_password.errors %}
                  {% for error in form.old_password.errors %}
                  <div class="text-danger pb-3" role="alert">
                      <p class="error-message">
                          <strong>{{ error|escape }}</strong>
                      </p>
                  </div>
                  {% endfor %}
                {% endif %}
                <div class="form-group">
                  <label for="id_new_password1">New Password <span class="required">*</span></label>
                  {{ form.new_password1 }}
                  <div class="js-validate-password1-error text-danger" role="alert" style="display: none;">
                  </div>
                </div>
                <div class="form-group">
                  <label for="id_new_password2">Confirm Password <span class="required">*</span></label>
                  {{ form.new_password2 }}
                  <div class="js-validate-password2-error text-danger" role="alert" style="display: none;">
                  </div>
                </div>
              </div>
            </div>
            <!-- Display new passwords error message -->
            {% if form.new_password2.errors %}
              {% for error in form.new_password2.errors %}
              <div class="text-danger pb-3" role="alert">
                  <p class="error-message">
                      <strong>{{ error|escape }}</strong>
                  </p>
              </div>
              {% endfor %}
            {% endif %}
            <div class="row">
              <div class="text-left col-12 col-sm-12 col-md-12 col-lg-12">
                <input type="submit" class="btn mb-3" value="Change Password" id="change-password">
              </div>
            </div>
          </form>
        </div>
      </div>
      <!--End Main Content-->
    </div>

  </div>
  <!--End Body Container-->

</div>
<!--End Page Wrapper-->

{% endblock content %}

{% block scripts %}

    <script src="{% static 'assets/js/custom/accounts/change_password.js' %}"></script>

{% endblock scripts %}

templates/accounts/password_reset.html
{% extends 'base.html' %}

{% block title %}
<title>Reset Password</title>
{% endblock title %}

{% block content %}

<div id="page-content">
  <!--Body Container-->
  <!--Breadcrumbs-->
  <div class="breadcrumbs-wrapper">
    <div class="container">
      <div class="breadcrumbs"><a href="{% url 'home:index' %}" title="Back to the home page">Home</a> <span
          aria-hidden="true">|</span> <span>Forgot Your Password</span></div>
    </div>
  </div>
  <!--End Breadcrumbs-->
  <!--Page Title with Image-->
  <div class="page-title">
    <h1>Retrieve your password here</h1>
  </div>
  <!--End Page Title with Image-->
  <div class="container">
    <div class="row">
      <!--Main Content-->
      <div class="col-12 col-sm-12 col-md-6 col-lg-6 box offset-md-3">
        <div class="mb-4">
          <form method="post" action="." accept-charset="UTF-8" class="contact-form">
            {% csrf_token %}
            <p>Please enter your email address below. You will receive a link to reset your password.</p>
            <div class="row">
              <div class="col-12 col-sm-12 col-md-12 col-lg-12">
                <div class="form-group">
                  <label for="id_email">Email Address <span class="required">*</span></label>
                  {{ form.email }}
                </div>
              </div>
            </div>
             <!-- Display email error message -->
              {% if form.errors %}
                {% for error in form.email.errors %}
                <div class="text-danger pb-3" role="alert">
                    <p class="error-message">
                        <strong>{{ error|escape }}</strong>
                    </p>
                </div>
                {% endfor %}
              {% endif %}
            <div class="row">
              <div class="text-left col-12 col-sm-12 col-md-12 col-lg-12">
                <input type="submit" class="btn mb-3" value="Submit">
                <p class="mb-4">
                  <a href="{% url 'accounts:login' %}">« Back To Login Page</a>
                </p>
              </div>
            </div>
          </form>
        </div>
      </div>
      <!--End Main Content-->
    </div>

  </div>
  <!--End Body Container-->

</div>
<!--End Page Wrapper-->

{% endblock content %}

templates/accounts/password_reset_done.html
{% extends 'base.html' %}

{% block title %}
    <title>Password Reset Done</title>
{% endblock title %}

{% block content %}

<div id="page-content">
    <!--Body Container-->
    <!--Breadcrumbs-->
    <div class="breadcrumbs-wrapper">
        <div class="container">
            <div class="breadcrumbs"><a href="{% url 'home:index' %}" title="Back to the home page">Home</a> <span
                    aria-hidden="true">|</span> <span>ٌPassword Reset Done</span>
            </div>
        </div>
    </div>
    <!--End Breadcrumbs-->
    <!--Page Title with Image-->
    <div class="page-title">
        <h1>ٌPassword Reset Done</h1>
    </div>
    <!--End Page Title with Image-->
    <div class="container">
        <div class="row">
            <!--Main Content-->
            <div class="col-12 col-sm-12 col-md-6 col-lg-6 box offset-md-3">
                <p>Your password has been changed successfully.</p>
                <div class="mb-4">
                    <div class="row">
                        <div class="text-left col-12 col-sm-12 col-md-12 col-lg-12">
                            <p>
                                <a href="{% url 'accounts:login' %}">« Back To Login Page</a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/accounts/password_reset_form.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>Recover Password</title>
{% endblock title %}

{% block content %}

<div id="page-content">
  <!--Body Container-->
  <!--Breadcrumbs-->
  <div class="breadcrumbs-wrapper">
    <div class="container">
      <div class="breadcrumbs"><a href="{% url 'home:index' %}" title="Back to the home page">Home</a> <span
          aria-hidden="true">|</span>
        {% if validlink %}
        <span>Recover Your Password</span>
        {% else %}
        <span>Password reset failed</span>
        {% endif %}
      </div>
    </div>
  </div>
  <!--End Breadcrumbs-->
  <!--Page Title with Image-->
  <div class="page-title">
    {% if validlink %}
    <h1>Recover your password</h1>
    {% else %}
    <h1>Password reset failed</h1>
    {% endif %}
  </div>
  <!--End Page Title with Image-->
  <div class="container">
    <div class="row">
      <!--Main Content-->
      <div class="col-12 col-sm-12 col-md-6 col-lg-6 box offset-md-3">
        {% if validlink %}
        <p>You are only one step a way from your new password, recover your password now.</p>
        <div class="mb-4">
          <form method="post" action="." accept-charset="UTF-8" class="contact-form">
            {% csrf_token %}
            <div class="row">
              <div class="col-12 col-sm-12 col-md-12 col-lg-12">
                <div class="form-group">
                  <label for="id_new_password1">New Password <span class="required">*</span></label>
                  {{ form.new_password1 }}
                  <div class="js-validate-password1-error text-danger" role="alert" style="display: none;">
                  </div>
                </div>
                <div class="form-group">
                  <label for="id_new_password2">Confirm Password <span class="required">*</span></label>
                  {{ form.new_password2 }}
                  <div class="js-validate-password2-error text-danger" role="alert" style="display: none;">
                  </div>
                </div>
              </div>
            </div>
            <!-- Display new passwords error message -->
            {% if form.errors %}
              {% for error in form.new_password2.errors %}
              <div class="text-danger pb-3" role="alert">
                  <p class="error-message">
                      <strong>{{ error|escape }}</strong>
                  </p>
              </div>
              {% endfor %}
            {% endif %}
            <div class="row">
              <div class="text-left col-12 col-sm-12 col-md-12 col-lg-12">
                <input type="submit" class="btn mb-3" value="Reset Password" id="change-password">
                <p class="mb-4">
                  <a href="{% url 'accounts:login' %}">« Back To Login Page</a>
                </p>
              </div>
            </div>
          </form>
          {% else %}
          <p>The password reset link was invalid, possibly because it has already been used. Please request a new
            password
            reset.</p>
          <p class="mb-1">
            <a class="text-danger" href="{% url 'password_reset' %}">Request a new password reset</a>
          </p>
          {% endif %}
        </div>
      </div>
      <!--End Main Content-->
    </div>

  </div>
  <!--End Body Container-->

</div>
<!--End Page Wrapper-->

{% endblock content %}

{% block scripts %}

  <script src="{% static 'assets/js/custom/accounts/change_password.js' %}"></script>

{% endblock scripts %}