cart/urls.py
from django.urls import path

from .views import cart_summary, cart_add, cart_update_delete

# namespace = cart

urlpatterns = [
    path('cart/', cart_summary, name='cart-summary'),
    path('ajax/cart/add/', cart_add, name='cart-add'),
    path('ajax/cart/update/delete/', cart_update_delete, name='cart-update-delete'),
]

checkout/urls.py
from django.urls import path

from checkout.views import checkout, create_order, update_delivery_cart, stripe_webhook, order_placed

# namespace = checkout

urlpatterns = [
    path('checkout/', checkout, name='checkout'),
    path("ajax/order/create/", create_order, name="ajax-create-order"),
    path("ajax/delivery/cart/update/", update_delivery_cart, name="ajax-update-delivery-cart"),
    path('webhooks/stripe/', stripe_webhook, name='stripe-webhook'),
    path('checkout/orderplaced/', order_placed, name='order-placed'),
]

faq/urls.py
from django.urls import path

from .views import faq

# namespace = faq

urlpatterns = [
    path('faqs/', faq, name='faq'),
]

home/urls.py
from django.urls import path

from .views import index

# namespace = home

urlpatterns = [
    path('', index, name='index'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static

from accounts.forms import (
        EmailValidationOnForgotPassword, 
        PasswordFieldsOnForgotPassword, 
        PasswordFieldsOnChangePassword,
    )


urlpatterns = [
    ## Django Admin
    path('admin/', admin.site.urls),

    ## Regular Endpoints
    # Accounts
    path('', include(('accounts.urls', 'accounts'), namespace='accounts')),
    # Product
    path('', include(('product.urls', 'product'), namespace='product')),
    # Cart
    path('', include(('cart.urls', 'cart'), namespace='cart')),
    # Order
    path('', include(('order.urls', 'order'), namespace='order')),
    # Checkout
    path('', include(('checkout.urls', 'checkout'), namespace='checkout')),
    # Home
    path('', include(('home.urls', 'home'), namespace='home')),
    # About
    path('', include(('about.urls', 'about'), namespace='about')),
    # FAQs
    path('', include(('faq.urls', 'faq'), namespace='faq')),
    
    # Password reset
    # 1- Submit password form                     // PasswordResetView.as_view() 
    # 2- Email sent success message               // PasswordResetDoneView.as_view()  
    # 3- Link to password reset form in email     // PasswordResetConfirmView.as_view() 
    # 4- password successfully changed message    // PasswordResetCompleteView.as_view()

    path('password/reset/', auth_views.PasswordResetView.as_view(
                                template_name='accounts/password_reset.html',
                                form_class=EmailValidationOnForgotPassword,),
                                name='password_reset'),
    path('password/reset/sent/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_sent.html',), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
                                template_name='accounts/password_reset_form.html',
                                form_class=PasswordFieldsOnForgotPassword,),
                                name='password_reset_confirm'),
    path('password/reset/complete/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_done.html',), name='password_reset_complete'),

    # Password change
    # 1- Submit password form                     // PasswordChangeView.as_view() 
    # 2- password successfully changed message    // PasswordChangeDoneView.as_view()
    path('password/change/', auth_views.PasswordChangeView.as_view(
                                template_name='accounts/password_change_form.html',
                                form_class=PasswordFieldsOnChangePassword,),
                                name='password_change'),
    path('password/change/complete/', auth_views.PasswordChangeDoneView.as_view(template_name='accounts/password_change_done.html',), name='password_change_done'),

    # Category
    path('', include(('category.urls', 'category'), namespace='category')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/views.py
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse
from django.template.loader import render_to_string

from product.models import Variation
from .cart import Cart


def cart_summary(request):
    """
    Display user's cart summary.
    """
    return render(request, 'cart/cart_summary.html', {})

def cart_add(request):
    """
    Add item to cart.
    """
    cart = Cart(request)
    product_id = int(request.POST.get("product_id"))
    size_id = int(request.POST.get("size_id"))
    color_id = int(request.POST.get("color_id"))
    product_variation = Variation.objects.filter(product__id=product_id, size__id=size_id, color__id=color_id).first()
    product_variation_qty = int(request.POST.get("product_qty"))
    cart.add(variation_id=product_variation.id, qty=product_variation_qty, variation_actual_price=product_variation.actual_price)
    data = dict() 
    data['html_mini_cart_data'] = render_to_string('cart/includes/partial_mini_cart.html', {'cart':cart})
    data['qty'] = cart.__len__()
    return JsonResponse(data)
   
def cart_update_delete(request):
    """
    Update and delete item from cart.
    """
    cart = Cart(request)
    variation_id = int(request.POST.get("variation_id"))
    data = dict()
    # update item.
    if request.POST.get('action') == 'update':
        product_variation_qty = int(request.POST.get("product_qty"))
        cart.add(variation_id=variation_id, qty=product_variation_qty)
        data['item_total_price'] = cart.get_item_total_price(variation_id)
        data['cart_total_price'] = cart.get_total_price() 
    # delete item.
    elif request.POST.get('action') == 'delete':
        cart.delete(variation_id=variation_id)
        context = {'cart':cart}
        data['html_mini_cart_data'] = render_to_string('cart/includes/partial_mini_cart.html', context)
        data['html_cart_data'] = render_to_string('cart/includes/partial_cart_summary.html', context)
    data['cart_qty'] = cart.__len__()
    return JsonResponse(data)   

templates/cart/includes/partial_cart_summary.html
{% load static %}

{% if cart|length %}
<div class="col-12 col-sm-12 col-md-8 col-lg-8 main-col">
    <form action="." method="post" class="cart style2">
        {% csrf_token %}
        <table>
            <thead class="cart__row cart__header">
                <tr>
                    <th colspan="2" class="text-center">Product</th>
                    <th class="text-center">Price</th>
                    <th class="text-center">Quantity</th>
                    <th class="text-right">Total</th>
                    <th class="action">Update</th>
                    <th class="action">Delete</th>
                </tr>
            </thead>
            <tbody>
                {% for item in cart %}
                <tr class="cart__row border-bottom line1 cart-flex border-top product-item" data-index="{{ item.variation_id }}">
                    <td class="cart__image-wrapper cart-flex-item">
                        <a href="{{ item.variation_product_url }}"><img class="cart__image"
                            src="{{ item.variation_image }}"
                            alt="{{ item.variation_product_name|title }} - {{ item.variation_color|title }} / {{ variation.size.name }}"></a>
                    </td>
                    <td class="cart__meta small--text-left cart-flex-item">
                        <div class="list-view-item__title">
                            <a href="{{ item.variation_product_url }}">{{ item.variation_product_name|title }} </a>
                        </div>

                        <div class="cart__meta-text">
                            Color: {{ item.variation_color|title }}<br>Size: {{ item.variation_size|upper }}<br>
                        </div>
                    </td>
                    <td class="cart__price-wrapper cart-flex-item">
                        <span class="money">${{ item.variation_actual_price }}</span>
                    </td>
                    <td class="cart__update-wrapper cart-flex-item text-right">
                        <div class="cart__qty text-center">
                            <div class="qtyField">
                                <a class="qtyBtn minus" href="javascript:void(0);"><i
                                        class="icon icon-minus"></i></a>
                                <input class="cart__qty-input qty" type="text" name="updates[]" id="qty{{ item.variation_id }}"
                                    value="{{ item.qty }}" pattern="[0-9]*">
                                <a class="qtyBtn plus" href="javascript:void(0);"><i
                                        class="icon icon-plus"></i></a>
                            </div>
                        </div>
                    </td>
                    <td class="text-right small--hide cart-price">
                        <div><span>$<span class="money" id="item-total-price{{ item.variation_id }}">{{ item.total_price }}</span></span></div>
                    </td>
                    <td class="text-center small--hide item-update">
                        <button type="button" name="update" class="btn btn--secondary edit-i bg-white update-cart-btn" data-url="{% url 'cart:cart-update-delete' %}"
                            data-index="{{ item.variation_id }}" title="Update">
                            <i class="fa fa-refresh"></i>
                        </button>
                    </td>
                    <td class="text-center small--hide item-delete">
                        <button type="button" name="delete" class="btn btn--secondary cart__remove bg-white mt-0 mr-0 delete-cart delete-from-cart-btn" data-url="{% url 'cart:cart-update-delete' %}"
                            data-index="{{ item.variation_id }}" title="Remove">
                            <i class="fa fa-close"></i>
                        </button>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="3" class="text-left"><a href="{% url 'home:index' %}"
                            class="btn--link cart-continue"><i class="icon icon-arrow-circle-left"></i>
                            Continue shopping</a>
                    </td>
                </tr>
            </tfoot>
        </table>
    </form>
</div>
<div class="col-12 col-sm-12 col-md-4 col-lg-4 cart__footer">
    <div class="cart-note">
        <div class="solid-border">
            <h5><label for="CartSpecialInstructions" class="cart-note__label small--text-center">Add a note
                    to your order</label></h5>
            <textarea name="note" id="CartSpecialInstructions" class="cart-note__input"></textarea>
        </div>
    </div>
    <div class="solid-border">
        <div class="row">
            <span class="col-12 col-sm-6 cart__subtotal-title"><strong>Subtotal</strong></span>
            <span class="col-12 col-sm-6 cart__subtotal-title cart__subtotal text-right">$<span
                    class="money cart-total-price" id='cart-total-price'>{{ cart.get_total_price }}</span></span>
        </div>
        <div class="cart__shipping">Shipping &amp; taxes calculated at checkout</div>
        <p class="cart_tearm">
            <label>
                <input type="checkbox" name="tearm" id="cartTearm" class="checkbox" value="tearm" required>
                I agree with the terms and conditions</label>
        </p>
        <a href="{% url 'checkout:checkout' %}"><button id="cart-checkout" class="btn btn--small-wide checkout">Proceed To Checkout</button></a>
        <div class="paymnet-img"><img src="{% static 'assets/images/payment-img.jpg' %}" alt="Payment"></div>
    </div>

</div>
{% else %}
<div class="cart-empty-state d-flex align-items-center justify-content-center flex-column">
    <i class="fa fa-shopping-cart"></i>
    <p class="cart-empty-state-text">Your Shopping Cart is Empty.</p>
    <a href="{% url 'home:index' %}"><button class="btn mt-1">Continue Shopping</button></a>
</div>
{% endif %}

templates/cart/includes/partial_mini_cart.html
<div class="modal-dialog">
    <div class="modal-content">
        <div id="cart-drawer" class="block block-cart">
            <a href="javascript:void(0);" class="close-cart" data-dismiss="modal" aria-label="Close"><i
                    class="anm anm-times-r"></i>
            </a>
            {% with total_qty=cart|length %} 
            <h4>Shopping Cart
                <span>(<span class='cart-qty-count'>{{ total_qty }}</span>
                <span class='cart-qty-count-items'>Item{{ total_qty|pluralize }}</span>)
                </span>
            </h4>
            {% if total_qty %}
            <div class="minicart-content">
                <ul class="clearfix">
                    {% for item in cart %}
                    <li class="item clearfix product-item" data-index="{{ item.variation_id }}">
                        <a class="product-image" href="{{ item.variation_product_url }}">
                            <img src="{{ item.variation_image }}" alt="" title="">
                        </a>
                        <div class="product-details">
                            <button type="button" name="delete" class="btn btn--secondary remove bg-white delete-from-cart-btn" data-url="{% url 'cart:cart-update-delete' %}"
                            data-index="{{ item.variation_id }}" title="Remove">
                            <i class="fa fa-close"></i>
                            </button>        
                            <a class="product-title" href="{{ item.variation_product_url }}">{{ item.variation_product_name|title }}</a>
                            <div class="variant-cart">{{ item.variation_color|title }} / {{ item.variation_size|upper }}</div>
                            <div class="wrapQtyBtn">
                                <div class="qtyField">
                                    <a class="qtyBtn minus" href="javascript:void(0);"><i
                                            class="anm anm-minus-r" aria-hidden="true"></i></a>
                                    <input type="text" name="quantity" value="{{ item.qty }}" class="qty" id="mini-qty{{ item.variation_id }}">
                                    <a class="qtyBtn plus" href="javascript:void(0);"><i
                                            class="anm anm-plus-r" aria-hidden="true"></i></a>
                                </div>
                            </div>
                            <div class="priceRow">
                                <div class="product-price">
                                    <span class="money">${{ item.variation_actual_price }}</span>
                                </div>
                            </div>
                        </div>
                    </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="minicart-bottom">
                <div class="subtotal list">
                    <span>Shipping:</span>
                    <span class="product-price">$10.00</span>
                </div>
                <div class="subtotal list">
                    <span>Tax:</span>
                    <span class="product-price">$05.00</span>
                </div>
                <div class="subtotal">
                    <span>Total:</span>
                    <span class="product-price">$<span class="cart-total-price">{{ cart.get_total_price }}</span></span>
                </div>
                <a href="{% url 'checkout:checkout' %}">
                    <button id="mini-cart-checkout" class="btn proceed-to-checkout">Proceed To Checkout</button>
                </a>
                <a href="{% url 'cart:cart-summary' %}">
                    <button type="button" class="btn btn-secondary cart-btn">View Cart</button>
                </a>
            </div>
            {% else %}
            <div class="cart-empty-state d-flex align-items-center justify-content-center flex-column">
                <i class="fa fa-shopping-cart"></i>
                <p class="cart-empty-state-text">Your Shopping Cart is Empty.</p>
            </div>
            {% endif %}
            {% endwith %}
        </div>
    </div>
</div>